name: Latest

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Scripts
        run: |-
          zip -r scripts.zip lib shared docs

      - name: Create or Replace latest Tag and Release
        uses: softprops/action-gh-release@v2
        with:
          name: latest
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is the "latest" release, which may not be fully stable.
            Please use it with caution.
          draft: false
          prerelease: true
          files: scripts.zip
