name: Latest

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "shared/**"

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Scripts
        run: |-
          zip -r scripts.zip lib shared docs

      # GitHub APIs take sometime to make effect, we should make sure before Recreate the Latest Release and Tag,
      # tag and release all get deleted. So we sleep sometime after deleting tag and release to wait for it taking effect.

      - name: Delete the Latest Release
        continue-on-error: true
        run: |
          gh release delete latest --repo $GITHUB_REPOSITORY
          sleep 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository_owner }}/${{ github.event.repository.name }}

      # Ignore the error when we delete the latest tag, it might not exist.
      - name: Delete the Latest Tag
        continue-on-error: true
        run: |
          gh api --method DELETE /repos/$GITHUB_REPOSITORY/git/refs/tags/latest
          sleep 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository_owner }}/${{ github.event.repository.name }}

      - name: Recreate the Latest Tag and Release
        uses: softprops/action-gh-release@v2
        with:
          name: latest
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is the "latest" release, which may not be fully stable.
            Please use it with caution.
          draft: false
          prerelease: true
          files: scripts.zip
