name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"

  workflow_call:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install make
        run: |
          sudo apt update -y
          sudo apt install make curl git -y

      - name: Run test
        run: |
          make docker/test
